logging:
  level:
    org:
      org:
        hibernate: DEBUG
      springframework:
        security: DEBUG
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss:SSS} %-5level [%thread] %logger{15} - %msg%n'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: zaim7579
    url: jdbc:mysql://127.0.0.1:3306/event_managment
    username: root
  thymeleaf:
      mode: HTML
      cache: false
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: true
    show-sql: true
  queries:
    users-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.id=ur.user_id) inner join role r on(ur.role_id=r.id) where u.email=?
    
#spring.queries.users-query=select email, password, active from user where email=?
#spring.queries.roles-query=select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
      